# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI and CD on main branch with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: docker_credentials

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: kan19/crud-department
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  publish:
    runs-on: ubuntu-latest
    environment: docker_credentials
    needs: build

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull latest build
      run: docker pull kan19/crud-department
      
    - name: Deploy to Docker Host
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: root@103.142.137.207
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY  }}
        deployment_mode: docker-compose
        args: up -d
        docker_prune: 'false'
        pull_images_first: 'false'


  
